version: '3'

services:

    flex-generator:
        container_name: 'flex-generator'
        build: .
        ports:
            - 3000:3000
        volumes:
            - ./app:/app
        command: npm start
